import { AuthProvider } from "./Providers";
import Footer from "../components/Footer"
import "./globals.css";
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'StockMovil',
  description: 'Generated by Next.js',
}
const inter = Inter({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"]
}) 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
