import { Inter } from "next/font/google";
import Footer from "../components/Footer"
import "./globals.css"
import "./App.css"

export const metadata = {
  title: 'StockMovil',
  description: 'Generated by Next.js',
}

const inter = Inter({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"]
}) 

export default function RootLayout({ children }) {
 return (
    <html lang="es">
      <body className={inter.className}>
        {children}
      </body>
      <footer>
        <Footer></Footer>
      </footer>
    </html>
  )
}
