
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>Stock Movil</title>
      </head>
      <body>
        <h1>NavBar</h1>
        <ul>
          <li>Home</li>
          <li>Mas</li>
        </ul>
        {children}
        </body>
    </html>
  )
}
